GET http://localhost:3001/api/users/

###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "Matti Luukkainen",
    "name": "Matti Luukkainen",
    "password": "salainen"
}

###
DELETE http://localhost:3001/api/users/65c27813d0e32c84bc338f42
Content-Type: application/json