GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content": "Ensure that everything still works",
    "important": true,
    "userId": "65aba4f47945f36a99dc3feb"
}

###
DELETE http://localhost:3001/api/notes/65c26a81e1f8416c72514e18
