GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "FullStackOpen is awesome!",
    "author": "David Bayode",
    "url": "example.com",
    "likes": "987654321"
}